spring:
  application:
    name: tea-zuul
server:
  port: 8091
zuul:
  ignored-services: "*"
  routes:
    mydept.serviceId: tea-provider
    mydept.path: /teaservice/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
