spring:
  application:
    name: good-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zy123456lk
    url: jdbc:mysql://127.0.0.1:3306/study?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
server:
  port: 8085
