server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: zuul-students
    prefer-ip-address: true
zuul:
  ignored-services: "*"
  routes:
    mystudents.serviceId: stu-provider
    mystudents.path: /myservice/**
  prefix: /students
spring:
  application:
    name: stu-zuul
